spring.application.name=SafarSaathiBackend
#DB config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/travelApp5?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
server.port=8080

# Razorpay Config
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SBJMbwhKPeMCP6}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:tJNblrH4eovTvZEr2Xy8Jeu4}

# SMTP Config (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patilshubham0830@gmail.com
spring.mail.password=${MAIL_PASSWORD:scvs irsa bifi dywd}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

